/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TenantsController_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminSettingsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminSettingsController_update"];
        trace?: never;
    };
    "/v1/admin/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MembersController_list"];
        put?: never;
        post: operations["MembersController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["MembersController_remove"];
        options?: never;
        head?: never;
        patch: operations["MembersController_updateRole"];
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminProductsController_list"];
        put?: never;
        post: operations["AdminProductsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminProductsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminProductsController_update"];
        trace?: never;
    };
    "/v1/admin/products/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminProductsController_archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/products/{id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminProductsController_addVariant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/products/variants/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AdminProductsController_removeVariant"];
        options?: never;
        head?: never;
        patch: operations["AdminProductsController_updateVariant"];
        trace?: never;
    };
    "/v1/admin/products/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminProductsController_attachImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/products/{id}/images/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminProductsController_reorderImages"];
        trace?: never;
    };
    "/v1/admin/products/images/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AdminProductsController_removeImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CollectionsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CollectionsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminCollectionsController_list"];
        put?: never;
        post: operations["AdminCollectionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/collections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminCollectionsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["AdminCollectionsController_remove"];
        options?: never;
        head?: never;
        patch: operations["AdminCollectionsController_update"];
        trace?: never;
    };
    "/v1/admin/collections/{id}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminCollectionsController_attachProducts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/collections/{id}/products/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminCollectionsController_reorderProducts"];
        trace?: never;
    };
    "/v1/admin/collections/{id}/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AdminCollectionsController_detachProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/content/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ContentController_home"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminContentController_list"];
        put?: never;
        post: operations["AdminContentController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/content/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminContentController_findOne"];
        put?: never;
        post?: never;
        delete: operations["AdminContentController_remove"];
        options?: never;
        head?: never;
        patch: operations["AdminContentController_update"];
        trace?: never;
    };
    "/v1/blog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BlogController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/blog/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BlogController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quiz/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["QuizController_recommend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cart/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CartController_price"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReviewsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminReviewsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/reviews/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminReviewsController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/reviews/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminReviewsController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/reviews/{id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminReviewsController_reply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminOrdersController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminOrdersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminOrdersController_update"];
        trace?: never;
    };
    "/v1/admin/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminOrdersController_updateStatus"];
        trace?: never;
    };
    "/v1/admin/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminSubscriptionsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminSubscriptionsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminSubscriptionsController_update"];
        trace?: never;
    };
    "/v1/admin/subscriptions/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminSubscriptionsController_pause"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/subscriptions/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminSubscriptionsController_resume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/subscriptions/{id}/skip-next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminSubscriptionsController_skipNext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/subscriptions/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminSubscriptionsController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/discount-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminPromotionsController_list"];
        put?: never;
        post: operations["AdminPromotionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/discount-codes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminPromotionsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["AdminPromotionsController_remove"];
        options?: never;
        head?: never;
        patch: operations["AdminPromotionsController_update"];
        trace?: never;
    };
    "/v1/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuditController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/audit-logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuditController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BrandingDto: {
            /** @example #3B2A1F */
            primary?: string;
            /** @example #C8642E */
            accent?: string;
            /** @example editorial */
            font?: string;
            /** @description URL del logo */
            logoUrl?: string;
        };
        ShippingSettingsDto: {
            /** @description Umbral de envío gratis (centavos COP) */
            freeShippingThresholdCents?: number;
            /** @description Tarifa plana de envío (centavos COP) */
            shippingFlatCents?: number;
        };
        UpdateSettingsDto: {
            name?: string;
            branding?: components["schemas"]["BrandingDto"];
            shipping?: components["schemas"]["ShippingSettingsDto"];
        };
        AddMemberDto: {
            /** @description Email del operador (se crea si no existe) */
            email: string;
            /** @description Nombre a mostrar (si el usuario es nuevo) */
            name?: string;
            /** @enum {string} */
            role: "TENANT_OWNER" | "TENANT_EDITOR" | "TENANT_ORDERS";
        };
        UpdateMemberRoleDto: {
            /** @enum {string} */
            role: "TENANT_OWNER" | "TENANT_EDITOR" | "TENANT_ORDERS";
        };
        LoginDto: {
            /** @example operador@origen.co */
            email: string;
        };
        CreateVariantDto: {
            /**
             * @description Gramos
             * @example 250
             */
            sizeGrams: number;
            /** @enum {string} */
            grind: "WHOLE_BEAN" | "ESPRESSO" | "FILTER" | "FRENCH_PRESS";
            /** @description Precio compra única (centavos COP) */
            priceOneTime: number;
            /** @description Precio suscripción (centavos COP) */
            priceSubscription?: number;
            /** @default 0 */
            stock: number;
        };
        CreateProductDto: {
            name: string;
            /** @description Slug URL-safe. Si se omite, se deriva del nombre. */
            slug?: string;
            /** @enum {string} */
            type: "BLEND" | "SINGLE_ORIGIN" | "DECAF";
            origin?: string;
            description?: string;
            producerStory?: string;
            /** @description Nivel de tostado */
            roastLevel: number;
            flavorNotes?: string[];
            badges?: string[];
            /**
             * @default DRAFT
             * @enum {string}
             */
            status: "ACTIVE" | "DRAFT" | "ARCHIVED";
            /**
             * @default YES
             * @enum {string}
             */
            subscriptionAvailability: "YES" | "NO" | "SUBSCRIPTION_ONLY";
            /** @description Variantes iniciales (opcional) */
            variants?: components["schemas"]["CreateVariantDto"][];
        };
        UpdateProductDto: {
            name?: string;
            /** @description Slug URL-safe. Si se omite, se deriva del nombre. */
            slug?: string;
            /** @enum {string} */
            type?: "BLEND" | "SINGLE_ORIGIN" | "DECAF";
            origin?: string;
            description?: string;
            producerStory?: string;
            /** @description Nivel de tostado */
            roastLevel?: number;
            flavorNotes?: string[];
            badges?: string[];
            /**
             * @default DRAFT
             * @enum {string}
             */
            status: "ACTIVE" | "DRAFT" | "ARCHIVED";
            /**
             * @default YES
             * @enum {string}
             */
            subscriptionAvailability: "YES" | "NO" | "SUBSCRIPTION_ONLY";
        };
        UpdateVariantDto: {
            /**
             * @description Gramos
             * @example 250
             */
            sizeGrams?: number;
            /** @enum {string} */
            grind?: "WHOLE_BEAN" | "ESPRESSO" | "FILTER" | "FRENCH_PRESS";
            /** @description Precio compra única (centavos COP) */
            priceOneTime?: number;
            /** @description Precio suscripción (centavos COP) */
            priceSubscription?: number;
            /** @default 0 */
            stock: number;
        };
        AttachImageDto: {
            /** @description URL pública (p.ej. tras subir a Vercel Blob) */
            url: string;
            alt?: string;
        };
        ReorderImagesDto: {
            /** @description IDs de imagen en el orden deseado */
            imageIds: string[];
        };
        AutoRulesDto: {
            /** @enum {string} */
            type?: "BLEND" | "SINGLE_ORIGIN" | "DECAF";
            /** @description Tostado mínimo (1..9) */
            roastLevelGte?: number;
            /** @description Tostado máximo (1..9) */
            roastLevelLte?: number;
            /** @description Nota de cata que debe contener */
            flavorNote?: string;
            /** @description Badge que debe contener */
            badge?: string;
        };
        CreateCollectionDto: {
            name: string;
            /** @description Slug; si se omite se deriva del nombre */
            slug?: string;
            description?: string;
            /**
             * @default MANUAL
             * @enum {string}
             */
            type: "MANUAL" | "AUTO";
            /** @description Reglas (solo type=AUTO) */
            rules?: components["schemas"]["AutoRulesDto"];
            /**
             * @description Orden en la navegación
             * @default 0
             */
            position: number;
        };
        UpdateCollectionDto: {
            name?: string;
            /** @description Slug; si se omite se deriva del nombre */
            slug?: string;
            description?: string;
            /**
             * @default MANUAL
             * @enum {string}
             */
            type: "MANUAL" | "AUTO";
            /** @description Reglas (solo type=AUTO) */
            rules?: components["schemas"]["AutoRulesDto"];
            /**
             * @description Orden en la navegación
             * @default 0
             */
            position: number;
        };
        AttachProductsDto: {
            /** @description IDs de producto a vincular */
            productIds: string[];
        };
        ReorderProductsDto: {
            /** @description IDs de producto en el orden deseado */
            productIds: string[];
        };
        CreateContentDto: {
            /** @enum {string} */
            kind: "ANNOUNCEMENT" | "HERO" | "SPOTLIGHT" | "FEATURED_BUNDLE";
            /** @description Payload del bloque; su forma se valida según `kind` */
            data: {
                [key: string]: unknown;
            };
            /** @default true */
            active: boolean;
            /** @description Inicio de vigencia (ISO) */
            startsAt?: string;
            /** @description Fin de vigencia (ISO) */
            endsAt?: string;
            /** @default 0 */
            position: number;
        };
        UpdateContentDto: {
            /** @description Nuevo payload; se valida según el `kind` del bloque */
            data?: {
                [key: string]: unknown;
            };
            active?: boolean;
            /** @description Inicio de vigencia (ISO) */
            startsAt?: Record<string, never> | null;
            /** @description Fin de vigencia (ISO) */
            endsAt?: Record<string, never> | null;
            position?: number;
        };
        QuizAnswersDto: {
            /** @enum {string} */
            roast?: "LIGHT" | "MEDIUM" | "DARK";
            /** @description Notas de cata preferidas */
            flavorNotes?: string[];
            /**
             * @description Tipo preferido
             * @enum {string}
             */
            type?: "BLEND" | "SINGLE_ORIGIN" | "DECAF";
            /** @description Prefiere descafeinado */
            decaf?: boolean;
            /**
             * @description Cuántas recomendaciones
             * @default 3
             */
            limit: number;
        };
        CartItemDto: {
            variantId: string;
            quantity: number;
        };
        PriceCartDto: {
            items: components["schemas"]["CartItemDto"][];
            /**
             * @default ONE_TIME
             * @enum {string}
             */
            mode: "ONE_TIME" | "SUBSCRIPTION";
            /** @description Código de descuento a aplicar */
            discountCode?: string;
        };
        CartLineDto: {
            variantId: string;
            productSlug: string;
            productName: string;
            sizeGrams: number;
            /** @enum {string} */
            grind: "WHOLE_BEAN" | "ESPRESSO" | "FILTER" | "FRENCH_PRESS";
            /** @description Precio unitario en centavos COP */
            unitCents: number;
            quantity: number;
            lineCents: number;
            /** @description Stock insuficiente para la cantidad pedida */
            outOfStock: boolean;
        };
        CartDiscountDto: {
            code: string;
            valid: boolean;
            amountCents: number;
            reason?: string;
        };
        CartPriceResponseDto: {
            lines: components["schemas"]["CartLineDto"][];
            subtotalCents: number;
            discountCents: number;
            shippingCents: number;
            totalCents: number;
            /** @description Faltó stock en alguna línea */
            hasStockIssues: boolean;
            discount?: components["schemas"]["CartDiscountDto"];
        };
        CreateReviewDto: {
            /** @description Slug del producto reseñado */
            productSlug: string;
            email: string;
            name?: string;
            rating: number;
            title?: string;
            body: string;
        };
        ApproveReviewDto: {
            /** @description Marcar como suscriptor verificado */
            verifiedSubscriber?: boolean;
        };
        ReplyReviewDto: {
            reply?: string;
        };
        UpdateOrderStatusDto: {
            /** @enum {string} */
            status: "RECEIVED" | "PREPARING" | "SHIPPED" | "DELIVERED" | "CANCELLED";
            /** @description URL de seguimiento (recomendada al pasar a SHIPPED) */
            trackingUrl?: string;
        };
        UpdateOrderDto: {
            /** @enum {string} */
            paymentStatus?: "PAID" | "PENDING" | "FAILED" | "REFUNDED";
            /** @description URL de seguimiento de envío */
            trackingUrl?: string;
            /** @description Notas internas (no visibles al cliente) */
            internalNotes?: string;
        };
        UpdateSubscriptionDto: {
            /** @description Frecuencia en días (7..365) */
            frequencyDays?: number;
            /** @description Descuento por suscripción (0..100) */
            discountPct?: number;
        };
        CreateDiscountCodeDto: {
            /**
             * @description Se normaliza a MAYÚSCULAS
             * @example BIENVENIDO10
             */
            code: string;
            /**
             * @default PERCENTAGE
             * @enum {string}
             */
            type: "PERCENTAGE" | "FIXED";
            /** @description PERCENTAGE: 1-100 · FIXED: centavos COP */
            value: number;
            /** @description Mínimo de compra en centavos */
            minSubtotalCents?: number;
            /** @description Tope de redenciones totales */
            maxRedemptions?: number;
            /** @default false */
            oneUsePerCustomer: boolean;
            /** @description Inicio de vigencia (ISO) */
            startsAt?: string;
            /** @description Fin de vigencia (ISO) */
            endsAt?: string;
            /** @default true */
            active: boolean;
        };
        UpdateDiscountCodeDto: {
            /**
             * @description Se normaliza a MAYÚSCULAS
             * @example BIENVENIDO10
             */
            code?: string;
            /**
             * @default PERCENTAGE
             * @enum {string}
             */
            type: "PERCENTAGE" | "FIXED";
            /** @description PERCENTAGE: 1-100 · FIXED: centavos COP */
            value?: number;
            /** @description Mínimo de compra en centavos */
            minSubtotalCents?: number;
            /** @description Tope de redenciones totales */
            maxRedemptions?: number;
            /** @default false */
            oneUsePerCustomer: boolean;
            /** @description Inicio de vigencia (ISO) */
            startsAt?: string;
            /** @description Fin de vigencia (ISO) */
            endsAt?: string;
            /** @default true */
            active: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_health: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantsController_current: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminSettingsController_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminSettingsController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembersController_list: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembersController_add: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembersController_remove: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembersController_updateRole: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_list: {
        parameters: {
            query?: {
                type?: "BLEND" | "SINGLE_ORIGIN" | "DECAF";
                /** @description Tostado mínimo (1..9) */
                roastMin?: number;
                /** @description Nota de cata a filtrar */
                flavorNote?: string;
                /** @description Slug de colección */
                collection?: string;
                limit?: number;
                /** @description Cursor keyset (id del último item) */
                cursor?: string;
            };
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catálogo público paginado del tenant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle de producto por slug */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminProductsController_list: {
        parameters: {
            query: {
                status: string;
                cursor: string;
            };
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminProductsController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminProductsController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminProductsController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminProductsController_archive: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminProductsController_addVariant: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVariantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminProductsController_removeVariant: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                variantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminProductsController_updateVariant: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                variantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVariantDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminProductsController_attachImage: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachImageDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminProductsController_reorderImages: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderImagesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminProductsController_removeImage: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                imageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CollectionsController_list: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Colecciones del tenant con conteo de productos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CollectionsController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Colección con sus productos resueltos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminCollectionsController_list: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminCollectionsController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCollectionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminCollectionsController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminCollectionsController_remove: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminCollectionsController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCollectionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminCollectionsController_attachProducts: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachProductsDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminCollectionsController_reorderProducts: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderProductsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminCollectionsController_detachProduct: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentController_home: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contenido vigente para Home A */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminContentController_list: {
        parameters: {
            query?: {
                kind?: "ANNOUNCEMENT" | "HERO" | "SPOTLIGHT" | "FEATURED_BUNDLE";
            };
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminContentController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminContentController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminContentController_remove: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminContentController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BlogController_list: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Cursor keyset (id del último post) */
                cursor?: string;
            };
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Posts publicados, paginados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BlogController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle del post */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    QuizController_recommend: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizAnswersDto"];
            };
        };
        responses: {
            /** @description Productos recomendados según el quiz */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CartController_price: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceCartDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartPriceResponseDto"];
                };
            };
        };
    };
    ReviewsController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewDto"];
            };
        };
        responses: {
            /** @description Reseña creada en estado PENDING */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminReviewsController_list: {
        parameters: {
            query: {
                status: string;
            };
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminReviewsController_approve: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminReviewsController_reject: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminReviewsController_reply: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminOrdersController_list: {
        parameters: {
            query?: {
                status?: "RECEIVED" | "PREPARING" | "SHIPPED" | "DELIVERED" | "CANCELLED";
                paymentStatus?: "PAID" | "PENDING" | "FAILED" | "REFUNDED";
                /** @description Filtra por cliente (id) */
                customerId?: string;
                /** @description Cursor keyset (id del último item) */
                cursor?: string;
                limit?: number;
            };
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminOrdersController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminOrdersController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminOrdersController_updateStatus: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminSubscriptionsController_list: {
        parameters: {
            query?: {
                status?: "ACTIVE" | "PAUSED" | "SKIPPED_NEXT" | "CANCELLED" | "PAYMENT_FAILED";
                /** @description Filtra por cliente (id) */
                customerId?: string;
                /** @description Cursor keyset (id del último item) */
                cursor?: string;
                limit?: number;
            };
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminSubscriptionsController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminSubscriptionsController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubscriptionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminSubscriptionsController_pause: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminSubscriptionsController_resume: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminSubscriptionsController_skipNext: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminSubscriptionsController_cancel: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminPromotionsController_list: {
        parameters: {
            query?: {
                /** @description Filtra por estado activo */
                active?: boolean;
            };
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminPromotionsController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDiscountCodeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminPromotionsController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminPromotionsController_remove: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminPromotionsController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDiscountCodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuditController_list: {
        parameters: {
            query?: {
                /** @description Filtra por entidad (p.ej. "products") */
                entity?: string;
                /** @description Filtra por id de la entidad afectada */
                entityId?: string;
                /** @description Filtra por operador (userId) */
                userId?: string;
                /** @description Método HTTP (POST/PATCH/DELETE) */
                action?: string;
                /** @description Desde (ISO, inclusive) */
                from?: string;
                /** @description Hasta (ISO, inclusive) */
                to?: string;
                /** @description Cursor keyset (id del último item) */
                cursor?: string;
                limit?: number;
            };
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuditController_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description Slug del tenant (lo pega el SDK del front) */
                "X-Tenant-Slug"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
